// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGgNzYN5RxDM9ofXA5XasdzqDWAjAmZmc',
    appId: '1:923840009509:web:86b5a95f62b7f2f12df6cc',
    messagingSenderId: '923840009509',
    projectId: 'swishdating-80a72',
    authDomain: 'swishdating-80a72.firebaseapp.com',
    storageBucket: 'swishdating-80a72.appspot.com',
    measurementId: 'G-X1RSKLKSYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsgzllkHTD1jEnKjsN-PwW5T7KHyKZJcA',
    appId: '1:923840009509:android:9b6b372c293e1b5f2df6cc',
    messagingSenderId: '923840009509',
    projectId: 'swishdating-80a72',
    storageBucket: 'swishdating-80a72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWFWUxcdqY4YBYFawBdkKF_fqouQDfRBw',
    appId: '1:923840009509:ios:72c0f15bf57b77652df6cc',
    messagingSenderId: '923840009509',
    projectId: 'swishdating-80a72',
    storageBucket: 'swishdating-80a72.appspot.com',
    iosClientId: '923840009509-ebo3beedv577cit1dhh6lg9vid0q91j7.apps.googleusercontent.com',
    iosBundleId: 'com.example.swish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWFWUxcdqY4YBYFawBdkKF_fqouQDfRBw',
    appId: '1:923840009509:ios:72c0f15bf57b77652df6cc',
    messagingSenderId: '923840009509',
    projectId: 'swishdating-80a72',
    storageBucket: 'swishdating-80a72.appspot.com',
    iosClientId: '923840009509-ebo3beedv577cit1dhh6lg9vid0q91j7.apps.googleusercontent.com',
    iosBundleId: 'com.example.swish',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGgNzYN5RxDM9ofXA5XasdzqDWAjAmZmc',
    appId: '1:923840009509:web:a8af60a62c4485fa2df6cc',
    messagingSenderId: '923840009509',
    projectId: 'swishdating-80a72',
    authDomain: 'swishdating-80a72.firebaseapp.com',
    storageBucket: 'swishdating-80a72.appspot.com',
    measurementId: 'G-8PF6EG8RYX',
  );
}
